### ISSUE TITLE
Rodauth 2.0 dependency?

### ISSUE THREAD

**Issue by qnm** [janko/rodauth-rails#1]
Hi!

This looks super interesting. We already have a cobbled together rails-roda implementation and I'm keen to try this, but the `spec.add_dependency "rodauth", "~> 2.0"` makes me think I'm missing something!

Is that deliberate?

**Comment by janko** [comment]
The next version of Rodauth will be 2.0. I’m currently pulling Rodauth from master in my application, but Jeremy said he added all the features he planned for 2.0, so we can expect a release soon 🤞

To reduce the amount of work needed to get rodauth-rails released, I’ve decided to target Rodauth 2.x, at least for now.

**Comment by janko** [comment]
rodauth-rails has finally been released, and in addition to Rodauth 2.x it also supports the latest 1.x version (1.23).
