### ISSUE TITLE
Add note to "JSON API" wiki page regarding Rails api mode

### ISSUE THREAD

**Issue by unkmas** [janko/rodauth-rails#115]
If you using Rails in API-mode it doesn't use sessions by default. So json without jwt won't work, until you enable session store.

Maybe, you can consider adding something like this to wiki page:

Note: if your Rails app is in the api mode, you need to enable session store in your `application.rb`:
```
    config.session_store :cookie_store, key: '_your_app_api_session'
    config.middleware.use ActionDispatch::Cookies
    config.middleware.use config.session_store, config.session_options
```

**Comment by janko** [comment]
Good point, would you mind updating the wiki page (it's publicly editable)?
