### ISSUE TITLE
Facebook / Third-Party Auth Documentation or Example

### ISSUE THREAD

**Issue by jackspiva** [janko/rodauth-rails#16]
Hi! I've been working on migrating our medium-sized app from Devise to Rodauth and it has been going really well so far. However, I have had some trouble finding a guide or example of facebook or other third-party auth providers being used with rodauth-rails. Is there any way we could add something to the README or include something in the demo app maybe? 

Wish I could help contribute this but I've been struggling a bit to understand the process of adding facebook authentication, and the only information on it I've been able to find it is the short example in the (rodauth readme)[https://github.com/jeremyevans/rodauth] which is a little unclear to me. 

Thanks! Let me know if there's anything I can do to help with this.

**Comment by janko** [comment]
Yeah, OmniAuth integration has been on my radar for some time, in the long term I would like to create a Rodauth extension for it, but in the short term a section in the README would be useful, I agree. I will try to add one tomorrow.

Just curious, how are you integrating with Facebook so far with OmniAuth? As I understand, Devise doesn't offer much beside some sugar around OmniAuth configuration, so I'm assuming you're currently using some custom code to implement 3rd-party authentication?
