### ISSUE TITLE
Full passwordless experience

### ISSUE THREAD

**Issue by nicolas-besnard** [janko/rodauth-rails#181]
Hi,

I am trying to get a full passwordless experience. The idea, is for the user to only provide an email and a username, and never have to set a password.

I have been able to get that, but I cannot remove the password constraint. There's always a moment where I need to put a password.

Do you have any idea on how to achieved that?

**Comment by janko** [comment]
I believe you should be able to configure this by disabling setting password for registration and verification forms:

```rb
create_account_set_password? false
verify_account_set_password? false
```

This is mentioned in [this guide](http://rodauth.jeremyevans.net/rdoc/files/doc/guides/email_only_rdoc.html).
