### ISSUE TITLE
Generator to install rodauth using alternative accounts_table

### ISSUE THREAD

**Issue by bekicot** [janko/rodauth-rails#194]
running 
```
rails g rodauth:install users
```

should generate rodauth migrations, model, and configurations that works with `users` table.

**Comment by janko** [comment]
Thanks for the suggestion. This might be possible for the initial `rodauth:install` run, but how would this work for any subsequent `rodauth:migration` runs? It would have to inject `*_table` declarations into the Rodauth configuration, but how would it know where it should do that? If I would introduce this feature, it would have to be all the way.

**Comment by janko** [comment]
I will close this, because GitHub Issues are reserved for bug reports, discussions and feature requests should be posted on Discussions.
