### ISSUE TITLE
undefined method `create_database_authentication_functions' for Rodauth:Module

### ISSUE THREAD

**Issue by cj** [janko/rodauth-rails#20]
Hi,

I just tried rodauth-rails 0.7 with the a clean install of rails 6.1 and followed the setup instructions but ran into this error when enabling `use_database_authentication_functions? true`, I even tried adding `require 'rodauth'` to the migration file:

```
undefined method `create_database_authentication_functions' for Rodauth:Module
/app-template/db/migrate/20201210212807_create_rodauth_database_functions.rb:5:in `up'
```

**Comment by janko** [comment]
You need to `require "rodauth/migrations"` for these methods to be available. I missed that when writing the docs, updated the README now.
