### ISSUE TITLE
email_subject_prefix not being used

### ISSUE THREAD

**Issue by whysthatso** [janko/rodauth-rails#203]
is it possible that email subject creation is not honoring the content of 'email_subject_prefix' in a locale file?

the rodauth-i18n generator leaves the prefix empty, but when adding any string there, no changes are happening to the email subject. should 'email_subject_prefix' be defined somewhere besides the locale?

from the [docs](http://rodauth.jeremyevans.net/rdoc/files/doc/email_base_rdoc.html) i understand that feature is autoloaded. and i found the use [here](https://github.com/janko/rodauth-rails/blob/aeaa488af91b18ddc3552068a48b8ba8d4a2b255/lib/rodauth/rails/feature/email.rb#L15)

what else could i do to debug this?

**Comment by janko** [comment]
Yeah, the default rodauth-rails behavior will include the `email_subject_prefix`, but the mailer generated by `rodauth:install` doesn't use it. I should probably fix that. It's enough to just prepend the `email_subject_prefix` in [these lines](https://github.com/janko/rodauth-rails/blob/546d257d52fd1528f590495be5888a50fa043e9f/lib/generators/rodauth/templates/app/mailers/rodauth_mailer.rb.tt#L8) in your mailer.

**Comment by whysthatso** [comment]
ok
i've changed it like so:

`mail subject: "#{@rodauth.email_subject_prefix}#{@rodauth.verify_account_email_subject}"`

and that fixed it for me.
