### ISSUE TITLE
undefined method `allow_forgery_protection='

### ISSUE THREAD

**Issue by adilsoncarvalho** [janko/rodauth-rails#22]
Hello mate,

I am trying your standard configuration on my rails-api app, and I am getting this error below.

My code is running on `ruby@2.7.2`, `rails@6.1.0` and `rodauth-rails@0.7.0`.

```
NoMethodError (undefined method `allow_forgery_protection=' for #<RodauthController:0x000000000066d0>):
  
app/lib/rodauth_app.rb:146:in `block in <class:RodauthApp>'
```

It seems that there is something here that is triggering the problem

```ruby
class RodauthApp < Rodauth::Rails::App
  configure json: :only do
    # List of authentication features that are loaded.
    enable :create_account, :verify_account, :verify_account_grace_period,
      :login, :logout, :jwt,
      :reset_password, :change_password, :change_password_notify,
      :change_login, :verify_login_change,
      :close_account

  # lots of stuff

  route do |r|
    # the line below is the 146
    r.rodauth # route rodauth requests
  end

  # more stuff
end
```

**Comment by janko** [comment]
Thanks for the report. I'm assuming the RodauthController is a descendant of ActionController::API, correct? It seems I haven't handled this scenario properly, I will push a fix shortly with better tests.

**Comment by adilsoncarvalho** [comment]
Yeap, I reached exactly that controller: `ActionController::API`.

**Comment by adilsoncarvalho** [comment]
Thanks mate for this quick fix. I had the chance to test today, and now I can reach `rodauth` with no problems.

![image](https://user-images.githubusercontent.com/349796/103649916-5b092b80-4fb3-11eb-858e-54722d74b6af.png)
