### ISSUE TITLE
Handling Admin User

### ISSUE THREAD

**Issue by j-manu** [janko/rodauth-rails#23]
In devise when I want to have admin users, I create a separate model `AdminUser`. 
How do I handle that here?

**Comment by janko** [comment]
Assuming that you want special treatment for admin users, you would typically create a separate configuration and route prefix:

```rb
class RodauthApp < Rodauth::Rails::App
  # main users
  configure do
    # ...
  end

  # admin users
  configure(:admin) do
    enable ... # admin features
    prefix "/admin"
  end

  route do |r|
    # ...
    r.rodauth
    r.on("admin") { r.rodauth(:admin) } # route admin authentication requests
    # ...
  end
end
```

You should be able to reuse the main `accounts` table and other `account_*` tables for storing admin users. However, if you need things like separate email uniqueness validation, you can choose a different table:

```rb
configure(:admin) do
  # ...
  accounts_table :admin_accounts
  password_hash_table :admin_account_password_hashes
  # ... and so on ...
end
```
