### ISSUE TITLE
undefined method `-@' for :id:Symbol

### ISSUE THREAD

**Issue by KoellM** [janko/rodauth-rails#24]
Can't call model method after logged in.
```error: undefined method `-@' for :id:Symbol```

This error only occurs when using MySQL
https://github.com/KoellM/RodauthTest/actions/runs/475719274

Test: https://github.com/KoellM/RodauthTest/blob/main/test/integration/rodauth_test.rb

Error occurred since rodauth-0.3.1(sequel-activerecord_connection ~>1.0)
If use rodauth-0.3.0(sequel-activerecord_connection ~>0.3), no this error.

**Comment by janko** [comment]
Thanks for reporting. I've just released sequel-activerecord_connection 1.2.1 with a [fix](https://github.com/janko/sequel-activerecord_connection/commit/e7bdcc1f89192b0a5d4f7b8cd0e27b201f1185e4) for this issue. I've confirmed that the tests in your repository pass with this fix.

**Comment by janko** [comment]
I've also released sequel-activerecord_connection 1.2.2 which fixes this same error if performing an Active Record inside a Sequel transaction (most Rodauth before/after hooks run inside a Sequel transaction).
