### ISSUE TITLE
Should Default Account Status Be 'Unverified'?

### ISSUE THREAD

**Issue by basabin54** [janko/rodauth-rails#27]
Hello! First time issue submitter, so please forgive me if I've done something wrong 😅

I believe the default account status in the base migration generator should be 'unverified' instead of 'verified'.

In Rodauth's default DB config, the default is 1 which maps to 'unverified': http://rodauth.jeremyevans.net/rdoc/files/README_rdoc.html#label-Creating+tables

And in the docs on this gem in the section about moving the account statuses to their own table, it also recommends setting the default to 1 which maps to 'unverified': https://github.com/janko/rodauth-rails#account-statuses

Here's the line where I think the default needs to be changed to 'unverified':
https://github.com/janko/rodauth-rails/blob/a901acfe4dd693c167083d08d5b543be85f710a7/lib/generators/rodauth/migration/base.erb#L12

If you'd like me to submit a PR for it I can

**Comment by janko** [comment]
You're right, it should, good catch 👍

A pull request would be great 👍

**Comment by janko** [comment]
Addressed in https://github.com/janko/rodauth-rails/pull/28
