### ISSUE TITLE
Improve documentation to ease users' transition to this gem

### ISSUE THREAD

**Issue by nicolas-besnard** [janko/rodauth-rails#31]
Would you accept a PR to:

- Improve the `rodauth:migrations` to add a new parameter (`--account-name`?) to easily create new model / migration when using rodauth with multi configuration
- Add documentation on how to create new account programmatically
- Add documentation about the new `RodauthController` to create when using multiple accounts

**Comment by janko** [comment]
1. Yes, that sounds like a good idea 👍 I would maybe name the option just `--name`.
2. There is already an official [guide](http://rodauth.jeremyevans.net/rdoc/files/doc/guides/create_account_programmatically_rdoc.html) for this. Maybe we can link to it from the README (e.g. it would be useful in the testing section).
3. Yes, makes total sense that a new configuration would require a different controller (e.g. for rendering different views) 👍

**Comment by janko** [comment]
I will close this one and await the pull requests 😉
