### ISSUE TITLE
Login route can't be rendered for a separate Rodauth namespace/config

### ISSUE THREAD

**Issue by benoror** [janko/rodauth-rails#317]
Been following the docs & [test/rails_app](https://github.com/janko/rodauth-rails/tree/main/test/rails_app) to create a separate Rodauth config for my `/admin` namespace but I can't get the generated views to show up, getting:

> Unknown action
> 
> The action 'login' could not be found for Admin::RodauthController

<img width="330" alt="Screenshot 2024-09-06 at 4 43 50 p m" src="https://github.com/user-attachments/assets/96e0824b-7300-4223-9f17-5e5386995869">

The steps I followed are:

Generated the views with the `--name` parameter:

```bash
rails generate rodauth:views login --name admin

      create  app/views/admin/rodauth/_login_form.html.erb
      create  app/views/admin/rodauth/_login_form_footer.html.erb
      create  app/views/admin/rodauth/login.html.erb
      create  app/views/admin/rodauth/multi_phase_login.html.erb
```

Had pre-existing `/admin` namespace in routes.rb

```ruby
  namespace :admin do
    #... my pre-existing admin routes
  end
```

#### app/misc/rodauth_app.rb

```ruby
class RodauthApp < Rodauth::Rails::App
  # primary configuration
  configure RodauthMain

  # ENABLED secondary configuration
  configure RodauthAdmin, :admin

  route do |r|
    r.rodauth # route rodauth requests

    # ==> Secondary configurations
    r.rodauth(:admin) # route admin rodauth requests
  end
end
```

(At some point I thought it was related with https://github.com/janko/rodauth-rails/issues/34 but seems is not an issue anymore and adding `break` / `r.pass` won't fix it anyways)

#### app/misc/rodauth_admin.rb

```ruby
class RodauthAdmin < Rodauth::Rails::Auth
  configure do
    enable :jwt, :login, :logout, :become_account
    prefix "/admin"
    rails_controller { Admin::RodauthController }
  end
end
```

#### app/controllers/admin/rodauth_controller.rb

```ruby
class Admin::RodauthController < ApplicationController
end
```

I tried adding a `login` action to `Admin::RodauthController` but it renders a blank page instead of the generated login view

```ruby
class Admin::RodauthController < ApplicationController
  def login
    render :login
  end
end
```

<img width="446" alt="Screenshot 2024-09-06 at 4 56 19 p m" src="https://github.com/user-attachments/assets/3a196bfa-7916-4f6b-a4ca-2fc28af51050">

I feel like I am missing something fundamental, maybe missing on the example rails app

**Comment by benoror** [comment]
OK seems I was able to make it work by adding an admin `layout` based off [janko/rodauth-demo-rails](https://github.com/janko/rodauth-demo-rails)

```ruby
class Admin::RodauthController < ActionController::Base 
  layout "admin"
end
````

- [rodauth-demo-rails/app/controllers/admin/application_controller.rb](https://github.com/janko/rodauth-demo-rails/blob/e5592f2fbaeb2a566826e8914cb807bf58ae9294/app/controllers/admin/application_controller.rb#L2)
- [rodauth-demo-rails/app/views/layouts/admin.html.erb](https://github.com/janko/rodauth-demo-rails/blob/master/app/views/layouts/admin.html.erb)

<img width="745" alt="Screenshot 2024-09-06 at 5 20 24 p m" src="https://github.com/user-attachments/assets/c2e37a3b-d4e3-4090-a6b6-5e68ca342089">

* Added explicitly `ActionController::Base` since I am using Rails API only (`config.api_only = true`)

**Comment by janko** [comment]
Not sure why you were getting the "unknown action" error when you used the application layout. Maybe this is an opportunity for rodauth-rails to have a clearer error message. If you would post the (full) backtrace of the error, I could probably improve the DX here.
