### ISSUE TITLE
Restricting rodauth-rails to subdomain

### ISSUE THREAD

**Issue by gczh** [janko/rodauth-rails#319]
Hey there!

I've switched over from Devise to rodauth-rails for some time for a couple of rails projects and love it. It's much more modular and easier to move things around if needed.

A recent project of mine requires having rodauth constraints under `app.lvh.me:3000` for local development and on prod `app.website.com`.

The reason for this is that the app would live in the app subdomain, and the rest are all marketing pages. Users should only be allowed to authenticate themselves via the app subdomain, and have session cookies limited to that.

Have been looking through the docs for some time and tried various methods but can't seem to figure out how to make sure login only works in the `app` subdomain.

Appreciate any help if anyone knows how to do that 🙏

**Comment by gczh** [comment]
**Updates:**

I could probably do something with the following:

```ruby
class RodauthApp < Rodauth::Rails::App
  # primary configuration
  configure RodauthMain

  # secondary configuration
  # configure RodauthAdmin, :admin

  route do |r|
    # check if r is on subdomain
  end
end
```

However, I don't think rodauth routes would reflect that though so it might require some odd fix.

**Comment by janko** [comment]
Handling of Rodauth routes happens inside the `r.rodauth` call in the Rodauth app, so you can just avoid calling it unless the request is coming from the `app` subdomain:

```rb
class RodauthApp < Rodauth::Rails::App
  route do |r|
    if rails_request.subdomain == "app"
      r.rodauth # route rodauth requests
    end
  end
end
```

You should also probably make sure not to call any authentication methods on subdomains other than `app`, as those might try to redirect to a Rodauth route on the wrong subdomain.
