### ISSUE TITLE
'Invalid email' when creating user (even if creating works fine...)

### ISSUE THREAD

**Issue by k-graefenhain** [janko/rodauth-rails#324]
I created a new user via rodauth. The user is added to the database. However I get a validation message 'invalid user' in the ui. Happens for all email-adresses I tried, even gmail.com adresses.

log:
`Started POST "/create-account" for 127.0.0.1 at 2024-09-26 16:20:13 +0200
Processing by RodauthController#create_account as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "email"=>"test@test.com", "password"=>"[FILTERED]", "password-confirm"=>"[FILTERED]", "commit"=>"Create Account"}
  Sequel (0.9ms)  select version from PRODUCT_COMPONENT_VERSION where lower(product) like 'oracle%'
  ↳ app/misc/rodauth_app.rb:11:in `block in <class:RodauthApp>'
  Sequel (1.3ms)  SELECT * FROM "USERS" WHERE (("EMAIL" = 'test@test.com') AND ("STATUS" IN (1, 2))) FETCH NEXT 1 ROWS ONLY
  ↳ app/misc/rodauth_app.rb:11:in `block in <class:RodauthApp>'
  Sequel (1.8ms)  INSERT INTO "USERS" ("EMAIL", "STATUS", "PASSWORD_HASH") VALUES ('test@test.com', 1, '$argon2id$v=19$m=65536,t=2,p=1$/yaTEDWzpIjqQZ5qLhz6MA$w1Wr1bhXqNAi7UsVtQ1VzbC+kyvN6eEub4QUSUPxXjw')
  ↳ app/misc/rodauth_app.rb:11:in `block in <class:RodauthApp>'
  Rendering layout layouts/application.html.erb
  Rendering rodauth/create_account.html.erb within layouts/application
  Rendered rodauth/create_account.html.erb within layouts/application (Duration: 0.8ms | Allocations: 4194)
  Rendered layout layouts/application.html.erb (Duration: 1.5ms | Allocations: 4492)
Completed 422 Unprocessable Entity in 79ms (Views: 1.9ms | ActiveRecord: 4.1ms | Allocations: 8852)`

**Comment by janko** [comment]
It's possible that the Oracle enhanced adapter doesn't return the ID of the inserted account record, which would cause Rodauth to return an "invalid login" validation error. Could you verify whether this is true?
