### ISSUE TITLE
rails g rodauth:views ...this command generates an error

### ISSUE THREAD

**Issue by Tioneb12** [janko/rodauth-rails#333]
rails 7.2
ruby 3.3.6

rails g rodauth:views --css=tailwind
/Users/ben/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionmailer-7.2.2/lib/action_mailer/base.rb:632:in method_missing': undefined method preview_path=' for class ActionMailer::Base (NoMethodError)
Did you mean?  preview_paths=
               _view_paths=

**Comment by janko** [comment]
I couldn't reproduce it on the demo app. I think this is most likely coming from application code, because the generator doesn't call this method. Does your Rails app boot otherwise (you can try running `rails boot`)? Otherwise, could you try running the generator with `BACKTRACE=1`.

**Comment by Tioneb12** [comment]
Thank you for your feedback, I found the source of the problem, in case it can help someone else ;)

https://github.com/rspec/rspec-rails/pull/2706
