### ISSUE TITLE
changing email subject on password reset rquest

### ISSUE THREAD

**Issue by gismoog** [janko/rodauth-rails#58]
Hello,

I'am trying to change the email subject with

**reset_password_email_subject "Passwort zurücksetzen"**

**in lib/rodauth_app.rb.**

I also changed the mail template which works great, but the email subject still says "Reset password".

I would be very grateful for a tip.

**Comment by gismoog** [comment]
de:
  rodauth:
    reset_password_email_subject: "Passwort zurücksetzen"

does not work, too.

**Comment by janko** [comment]
The default rodauth-rails installation in recent versions sets up a custom mailer class, which doesn't use Rodauth settings, so this is where you configure subject, body and other.

**Comment by gismoog** [comment]
Yihhhaaaa!

Thanks - just found it ;-) 

Everything works now as expected.
