### ISSUE TITLE
Verify login change view generator missing

### ISSUE THREAD

**Issue by sic-f** [janko/rodauth-rails#60]
Can't generate the `verify-login-change` view through `rails generate rodauth:views`.

Would be great to be able to customize that page.

**Comment by janko** [comment]
Thanks for reporting, that was an oversight, it's now fixed on master 👍🏻

**Comment by sic-f** [comment]
> Thanks for reporting, that was an oversight, it's now fixed on master 👍🏻

Thanks for the quick fix 🙇‍♂️
