### ISSUE TITLE
undefined method flash=

### ISSUE THREAD

**Issue by andyrue** [janko/rodauth-rails#66]
I'm trying to use rodauth-rails in a rails api app. I've noticed a couple things about generating the rodauth install using the `--json` flag.

If I specify the generator to use `--json` it still enables `:jwt` in the rodauth_app file and includes a `jwt_secret`. I then get errors because it's expecting the jwt gem to be installed, which I'm not needing. The documentation makes it sound like I should only be getting all the jwt configurations if I specified `--jwt` with the generator.

Once I remove the `jwt_secret` and the `enable :jwt`, I stop getting jwt errors and start getting `undefined method flash=' for #<ActionDispatch::Request:0x00007fabaea1fd90>` when I try to post to `/login`. Since this is an api, I don't have a flash, and from reading through previous issues it sounds like this was fixed in version 0.4. I'm on 0.17.

This is on a fresh rails 6.1.4.1 api app. The only changes I have made are adding `rack-cors`, enabling cookies and session cookies in `application.rb`, and adding `include ActionController::RequestForgeryProtection` with `protect_from_forgery with: :null_session` in the application controller. 

On a side note, how can I inspect a request being sent to a rodauth route? I can't find a place to put a `byebug` call. My client is sending an `X-CSRF-Token` header with a good value, but I'm still getting `Can't verify CSRF token authenticity.` so I'm needing to troubleshoot that further, but that's not your problem. :-)

Thank you!

**Comment by andyrue** [comment]
It's strange. Everything related to Flash in the `rodauth_app` file is commented out. Is there another place I should be checking? It seems to be coming from the `r.rodauth` line in the routes block. That wasn't clear before, but it is now.

```
NoMethodError (undefined method `flash=' for #<ActionDispatch::Request:0x00007fd61a1059d0>):
app/lib/rodauth_app.rb:132:in `block in <class:RodauthApp>'
```

Line 132 is the `r.rodauth` inside the route block.

I did discover that if I remove `protect_from_forgery` from my `application_controller.rb` I no longer get the flash error, but instead I get:

  ```
NoMethodError (undefined method `new' for nil:NilClass):
  app/lib/rodauth_app.rb:132:in `block in <class:RodauthApp>'
```



I created another fresh app and installed rodauth-rails from master. The --json update worked as expected this time. Thanks for fixing that!

**Comment by janko** [comment]
> It's strange. Everything related to Flash in the rodauth_app file is commented out. Is there another place I should be checking?

The issue is that rodauth-rails activated flash integration when it apparently shouldn't have. The error is most likely not coming from Rodauth but from rodauth-rails.

> It seems to be coming from the r.rodauth line in the routes block. That wasn't clear before, but it is now.

The `r.rodauth` call routes Rodauth requests, so most Rodauth exceptions will originate from there. You likely have some backtrace filter that doesn't display the backtrace from gems, so that's why it appears as the first line.

> I did discover that if I remove protect_from_forgery from my application_controller.rb I no longer get the flash error, but instead I get:

I'm missing a full backtrace for this.

> I created another fresh app and installed rodauth-rails from master.

Would you mind sharing it? Being able to look at a Rails app that exhibits this error would guarantee me fixing it 😃

**Comment by andyrue** [comment]
Of course, I'm sorry I didn't do this sooner. https://github.com/andyrue/rodauth-test Thank you for looking.
