### ISSUE TITLE
RodAuth Route Prefix Ignored in Rails

### ISSUE THREAD

**Issue by andyrue** [janko/rodauth-rails#76]
It seems when configuring the RodAuth route prefix with `prefix "/auth"`, it's not working. I added the prefix to `rodauth_app.rb`, and the routes then appear to be correct when running `rails rodauth:routes`, but performing a request to `/auth/login` I get No route matches `"/auth/login"`. POSTing to `"/login"` does work, even though the rodauth routes list `/auth/**`. Restarting the server doesn't make a difference. Do I need to do something different to change where the rodauth routes are mounted?

**Comment by janko** [comment]
When using setting route prefix, you also need to change the

```rb
r.rodauth
```

to

```rb
r.on "auth" do
  r.rodauth
end
```

In the `route` block. I've been discussing with Jeremy the possibility of Rodauth automatically handling this for you, but so far we haven't agreed on a solution.

**Comment by andyrue** [comment]
D'oh! Thank you.
