### ISSUE TITLE
inconsistencies for rodauth.authenticated_by between controllers and RoadauthApp

### ISSUE THREAD

**Issue by nicolas-besnard** [janko/rodauth-rails#8]
This might be a `Rodauth` bug rather than a `rodauth-rails` one.

I've configured my RoadauthApp to use `OTP`.

```rb
class RodauthApp < Rodauth::Rails::App
  configure(json: true) do
    # List of authentication features that are loaded.
    enable :create_account, :verify_account, :verify_account_grace_period,
      :login, :remember, :logout,
      :close_account, :two_factor_base, :otp

  route do |r|
    rodauth.load_memory # autologin remembered users
    r.rodauth # route rodauth requests

    Rails.logger.info '  -- rodauth.authenticated_by'
    Rails.logger.info rodauth.authenticated_by.inspect
  end
end
```

When logging in, and entering OTP code:
- In controller: `rodauth.authenticated_by # => ["password", "totp"]`
- In RodauthApp: `rodauth.authenticated_by # => ["password", "totp"]`

So far, so good.

Now, I'm changing the "remember settings" by visiting `/remember`. When clicking "Remember me" then "Change Remember Setting", I still have the same output in the controller and in RoadauthApp (`rodauth.authenticated_by # => ["password", "totp"]`)

However, after modifying the remember setting and trying to access a protected resource:
- In controller: `rodauth.authenticated_by # => ["password", "totp"]`
- In RodauthApp: `rodauth.authenticated_by # => ["remember", "totp"]`

I'm not sure this is a bug, but the behavior seems weird.

I'll be happy to give you an app to reproduce this

**Comment by janko** [comment]
Thanks for the report. It's not likely that this is related to rodauth-rails, but an app that reproduces the issue would be great, because then we can find the problem and possibly send a patch to Rodauth.

**Comment by nicolas-besnard** [comment]
I have an app playground I am using to play with this lib. You will find it here: https://github.com/nicolas-besnard/rodauth-rails-otp

You should be able to see the reproduction. Let me know if there's any issue and I'll create a smaller app

**Comment by nicolas-besnard** [comment]
The [`base.rb`][1] file define a `session` method that use the `scope` of the app

On the other hand, [`jwt.rb`][2] redefines this method in case of a JSON request. Maybe this method should call `super` in case it's a JSON request but their not JWT token? I tried that locally and it's working. I'll need more time to see the impact of this change

[1]: https://github.com/jeremyevans/rodauth/blob/422a9dbb06e35340671641e407f1fc9de55fd295/lib/rodauth/features/base.rb#L141
[2]: https://github.com/jeremyevans/rodauth/blob/422a9dbb06e35340671641e407f1fc9de55fd295/lib/rodauth/features/jwt.rb#L43

**Comment by janko** [comment]
Good catch, yeah, that might the the issue. I don't yet fully understand why JWT is implemented this way (i.e. why does the session need to be cached in an instance variable).

**Comment by janko** [comment]
I'll consider this one resolved as you seem to have found the solution in https://github.com/jeremyevans/rodauth/issues/101.
